# Site
title: Mahir Chowdhury
bio: "Hey! I am currently studying BASc. Electrical Engineering at UWindsor and I am known as the Chair of the IEEE Windsor Student Branch\n"
description: "Electrical Engineering Student"
reading_time: true
words_per_minute: 300
logo: "assets/img/saitama.png"
background: "assets/img/wallpaper.jpg"
tiled_bg: false # Set this true if you want to tile your background image, otherwise it will be covered
locale: en_US
url: //mahirchow.github.io
# url: //localhost:4000

# Jekyll
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
#plus:            #username
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
# email: daiansask@gmail.com
# twitter:            username
# facebook:           username
github-url: mahirchow
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin: mahir-daian-chowdhury
#xing:              username
instagram: mahirchow
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              1bit2bytes
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
# resume: mahirchow

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
  base_url: https://github.com

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
  ]
